title: Mikkel Winther Pedersen
description: >
  Genetiker og geograf. Forsker og formidler med fokus på fortidens
  natur, klima og menneskers aktiviteter, undersøgt gennem analyser
  af gammelt DNA bevaret i jord og sedimenter.

baseurl: "/mikkelwintherpedersen.github.io"
url: "https://miwipe.github.io"

author:
  name: Mikkel Winther Pedersen

theme: minima

markdown: kramdown

plugins:
  - jekyll-seo-tag

lang: da
timezone: Europe/Copenhagen
